version: '2'

services:

  mongo_datavolume:
    image: busybox
    volumes:
      - /data/db
    entrypoint: /bin/true

  mongo:
    build: .
    restart: always
    ports:
      - "27017:27017"
    volumes_from:
      # busyboxでデータの永続化を行う
      - mongo_datavolume
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
